### ISSUE TITLE
Why did the version went from 3.1.0 to 3.0.9 ???

### ISSUE THREAD

**Issue by sunshineo** [danday74/envsub#11]
Thanks for the good work though

**Comment by danday74** [comment]
Sorry was a while since I published so don't know the answer - however, npm only lets you increment the version so I'm guessing you got the latest version just as I published some minor version with an error in the README or something - I then prob deleted this minor version, which npm only allows you to do for a few hours - a few hours after publishing you can no longer delete - hope this helps, I think its no major worry for you

**Comment by sunshineo** [comment]
![image](https://user-images.githubusercontent.com/1072766/63290256-eaeeee00-c275-11e9-8427-a876de7cce66.png)

**Comment by sunshineo** [comment]
Looking at the NPM version history it seems to be that 2 years ago, when published, 3.0.9 was jumped over but when the publish 7 months ago was out, it went back to 3.0.9.

OR, a more likely scenario: there was a 3.0.9 from 2 years ago, but 7 months ago, it got replaced by the latest. 

Either way, you are right that it is not a big deal. But is it possible that we can just publish a 3.1.1 for the latest so no one else needs to think about it again?

**Comment by danday74** [comment]
Hey there

Slow fix I know! Sorry!

I have released 4.0.1 today which upgrades dependencies to latest versions.

Support has been dropped for Node 6 - now supports Node 8 and up.

Closing this ticket. Thanks for your interest :)
